// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/privacy" | "/terms" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./privacy/page.jsx": {
    id: "privacy/page";
    page: "/privacy";
  };
  "./terms/page.jsx": {
    id: "terms/page";
    page: "/terms";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "privacy/page": typeof import("./src/app/./privacy/page.jsx");
  "terms/page": typeof import("./src/app/./terms/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};